[package]
name = "aoc2025"
version = "1.0.0"
edition = "2024"

[dependencies]
atty = "0.2"

[[bin]]
name = "day01_part1"
path = "src/bin/day01_part1.rs"

# [[bin]]
# name = "day01_part2"
# path = "src/bin/day01_part2.rs"
